# Generated by Django 4.2.6 on 2023-11-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cover_alter_review_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='cover_type',
            new_name='name',
        ),
    ]
