# Generated by Django 4.2.6 on 2023-11-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_cover_type_cover_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='name',
            new_name='cover_type',
        ),
    ]
