# Generated by Django 4.2.6 on 2023-11-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_name_cover_cover_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ManyToManyField(to='main_app.cover'),
        ),
    ]
